[package]
name = "s2n-tls-rust"
version = "0.1.0"
edition = "2024"

[dependencies]
s2n-tls-events = { path = "../s2n-tls-events" }
s2n-quic-core = { version = "0.61", features = ["testing"] }

[lib]
name = "s2n_rust"
crate-type = ["cdylib"]
