name: BSD

on:
  pull_request:
    branches:
      - main

jobs:
  testfreebsd:
    runs-on: macos-12
    name: FreeBSD
    steps:
      - uses: actions/checkout@v2
      - name: Build and test in FreeBSD
        id: test
        uses: vmactions/freebsd-vm@v0.3.0
        with:
          prepare: pkg install -y ninja cmake
          run: |
            freebsd-version
            mkdir build
            .github/s2n_bsd.sh build
      - name: Upload test results
        if: always()
        uses: actions/upload-artifact@master
        with:
          name: all_test_output
          path: |
            build/release/Testing/Temporary
            build/debug/Testing/Temporary
  testopenbsd:
    runs-on: macos-12
    name: OpenBSD
    steps:
      - uses: actions/checkout@v2
      - name: Build and test in OpenBSD
        id: test
        uses: vmactions/openbsd-vm@v0.1.2
        with:
          prepare: pkg_add ninja cmake
          run: |
            uname -rsv
            mkdir /home/build
            .github/s2n_bsd.sh /home/build
            mv /home/build build
          mem: 2048
      - name: Upload test results
        if: always()
        uses: actions/upload-artifact@master
        with:
          name: all_test_output
          path: |
            build/release/Testing/Temporary
            build/debug/Testing/Temporary
