---
name: Test Job

on:
  pull_request:
    branches:
      - main

jobs:
  compliance:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: goatgoose/duvet-action@v0.0.2
        with:
          report-script: compliance/generate_report.sh
